In [3]:
import torch

# Create a tensor with a single value
t1 = torch.tensor(4.)

torch.get_default_dtype()

torch.float32

In [5]:
initial_tensor = torch.rand(2,3)

initial_tensor

tensor([[0.4022, 0.9886, 0.3079],
        [0.5573, 0.9760, 0.5170]])

In [6]:
initial_tensor.fill_(10)

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [7]:
new_tensor = initial_tensor.add(2)
new_tensor

tensor([[12., 12., 12.],
        [12., 12., 12.]])

In [9]:
initial_tensor.add_(8)
initial_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [10]:
new_tensor.sqrt_()
new_tensor

tensor([[3.4641, 3.4641, 3.4641],
        [3.4641, 3.4641, 3.4641]])

In [12]:
x = torch.linspace(start=0.1,end=10.0, steps=15)
x

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

In [13]:
tensor_chunk = torch.chunk(x,3,0)
tensor_chunk

(tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286]),
 tensor([3.6357, 4.3429, 5.0500, 5.7571, 6.4643]),
 tensor([ 7.1714,  7.8786,  8.5857,  9.2929, 10.0000]))

In [15]:
tensor_chunk1 = tensor_chunk[0]
tensor_chunk2 = tensor_chunk[1]
tensor3 = torch.tensor([3.0,4.0,5.0])

torch.cat((tensor_chunk1,tensor_chunk2,tensor3),0)

tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286, 3.6357, 4.3429, 5.0500, 5.7571,
        6.4643, 3.0000, 4.0000, 5.0000])

In [16]:
random_tensor = torch.Tensor([[1,2,3],[4,5,6],[7,8,9]])
random_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [17]:
random_tensor[1:,1:]

tensor([[5., 6.],
        [8., 9.]])

In [18]:
random_tensor.size()

torch.Size([3, 3])

In [19]:
resized_tensor = random_tensor.view(9)
resized_tensor

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [24]:
resized_tensor = random_tensor.view(-1,3)
resized_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [28]:
random_tensor[2,2] = 100
resized_tensor

tensor([[ 10.,   2.,   3.],
        [  4.,   5.,   6.],
        [  7.,   8., 100.]])

In [29]:
random_tensor

tensor([[ 10.,   2.,   3.],
        [  4.,   5.,   6.],
        [  7.,   8., 100.]])

In [30]:
random_tensor.shape

torch.Size([3, 3])

In [31]:
tensor_unsqueeze = torch.unsqueeze(random_tensor,2)
tensor_unsqueeze

tensor([[[ 10.],
         [  2.],
         [  3.]],

        [[  4.],
         [  5.],
         [  6.]],

        [[  7.],
         [  8.],
         [100.]]])

In [32]:
tensor_unsqueeze.shape

torch.Size([3, 3, 1])

In [35]:
initial_tensor

tensor([[18., 18., 18.],
        [18., 18., 18.]])

In [34]:
tensor_transpose = torch.transpose(initial_tensor,0,1)
tensor_transpose

tensor([[18., 18.],
        [18., 18.],
        [18., 18.]])

In [36]:
random_tensor

tensor([[ 10.,   2.,   3.],
        [  4.,   5.,   6.],
        [  7.,   8., 100.]])

In [37]:
sorted_tensor, sorted_indices = torch.sort(random_tensor)

In [38]:
sorted_tensor

tensor([[  2.,   3.,  10.],
        [  4.,   5.,   6.],
        [  7.,   8., 100.]])

In [41]:
sorted_indices

tensor([[1, 2, 0],
        [0, 1, 2],
        [0, 1, 2]])

In [43]:
tensor_float = torch.FloatTensor([[-1,2,3],[4,-5,6],[7,-8,9]])
tensor_float

tensor([[-1.,  2.,  3.],
        [ 4., -5.,  6.],
        [ 7., -8.,  9.]])

In [44]:
tensor_float.abs()

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [49]:
rand1 = torch.abs(torch.randn(2,3))
rand2 = torch.abs(torch.randn(2,3))
rand1

tensor([[0.2560, 1.6423, 0.3746],
        [0.4543, 0.9817, 0.2868]])

In [50]:
rand2

tensor([[0.2544, 0.4743, 0.8324],
        [1.5740, 1.0467, 1.1746]])

In [51]:
add1 = rand1 + rand2
add1

tensor([[0.5104, 2.1166, 1.2070],
        [2.0283, 2.0284, 1.4615]])

In [52]:
tensor_float = torch.FloatTensor([[-1,2,3],[4,-5,6],[7,-8,9]])
tensor_div = torch.div(tensor_float,tensor_float+0.3)
tensor_div

tensor([[1.4286, 0.8696, 0.9091],
        [0.9302, 1.0638, 0.9524],
        [0.9589, 1.0390, 0.9677]])

In [53]:
tensor_mul = torch.mul(tensor_float,tensor_float)
tensor_mul

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])

In [54]:
tensor_clamp = torch.clamp(tensor_float,min=0.1,max=0.8)
tensor_clamp

tensor([[0.1000, 0.8000, 0.8000],
        [0.8000, 0.1000, 0.8000],
        [0.8000, 0.1000, 0.8000]])

In [56]:
t1 = torch.Tensor([1,2])
t2 = torch.Tensor([1,2])

dot_product = torch.dot(t1,t2)
dot_product

tensor(5.)

In [58]:
matrix = torch.Tensor([[1,2,3],[4,5,6]])
vector = torch.Tensor([0,1,2])

matrix_vector = torch.mv(matrix,vector)
matrix_vector

tensor([ 8., 17.])

In [62]:
torch.argmax(matrix, dim=1)


tensor([0, 0])

In [64]:
type(matrix.numpy())


numpy.ndarray

In [65]:
torch.is_tensor(matrix)

True

In [66]:
torch.is_tensor(matrix.numpy())

False

In [68]:
import numpy as np
numpy_arr = np.array([1,2,3,4,5])

numpy_arr

array([1, 2, 3, 4, 5])

In [69]:
tensor_from_numpy = torch.from_numpy(numpy_arr)
tensor_from_numpy

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [70]:
torch.is_tensor(tensor_from_numpy)

True

Numpy and Tensor share the same memory. 

To avoid making copies of underlying data:

In [71]:
tensor_from_array = torch.as_tensor(numpy_arr)
tensor_from_array

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

To make copies of the underlying data:

In [73]:
tensor_from_array_2 = torch.tensor(numpy_arr)
tensor_from_array_2

tensor([1, 2, 3, 4, 5], dtype=torch.int32)